var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import styled from 'styled-components';
import { theme as typeColors } from 'config/themes';
export var ToastElement = styled.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  background-color: ", ";\n  color: ", ";\n  transition: 0.3s ease;\n  position: relative;\n  pointer-events: auto;\n  overflow: hidden;\n  margin: 0 0 6px;\n  padding: 30px;\n  margin-bottom: 15px;\n  max-height: 100px;\n  border-radius: 8px;\n  opacity: 0.9;\n  background-position: 15px;\n  background-repeat: no-repeat;\n  min-height: 50px;\n  max-width: 380px;\n  padding: 20px 15px 10px 10px;\n  &:hover {\n    // box-shadow: 0 0 3px #fff;\n    opacity: 1;\n    cursor: pointer;\n  }\n  button {\n    position: relative;\n    right: -0.3em;\n    top: -0.3em;\n    float: right;\n    font-weight: 700;\n    color: ", ";\n    outline: none;\n    border: none;\n    text-shadow: 0 1px 0 #fff;\n    opacity: 0.8;\n    line-height: 1;\n    font-size: 16px;\n    padding: 0;\n    cursor: pointer;\n    background: 0 0;\n    border: 0;\n  }\n"], ["\n  background-color: ", ";\n  color: ", ";\n  transition: 0.3s ease;\n  position: relative;\n  pointer-events: auto;\n  overflow: hidden;\n  margin: 0 0 6px;\n  padding: 30px;\n  margin-bottom: 15px;\n  max-height: 100px;\n  border-radius: 8px;\n  opacity: 0.9;\n  background-position: 15px;\n  background-repeat: no-repeat;\n  min-height: 50px;\n  max-width: 380px;\n  padding: 20px 15px 10px 10px;\n  &:hover {\n    // box-shadow: 0 0 3px #fff;\n    opacity: 1;\n    cursor: pointer;\n  }\n  button {\n    position: relative;\n    right: -0.3em;\n    top: -0.3em;\n    float: right;\n    font-weight: 700;\n    color: ", ";\n    outline: none;\n    border: none;\n    text-shadow: 0 1px 0 #fff;\n    opacity: 0.8;\n    line-height: 1;\n    font-size: 16px;\n    padding: 0;\n    cursor: pointer;\n    background: 0 0;\n    border: 0;\n  }\n"])), function (pr) { return typeColors[pr.type].bgColor; }, function (pr) { return typeColors[pr.type].color; }, function (pr) { return typeColors[pr.type].color; });
export var ToastTitle = styled.p(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  font-weight: 700;\n  font-size: 15px;\n  text-align: left;\n  margin-top: 0;\n  margin-bottom: 6px;\n  width: 300px;\n  height: 18px;\n"], ["\n  font-weight: 700;\n  font-size: 15px;\n  text-align: left;\n  margin-top: 0;\n  margin-bottom: 6px;\n  width: 300px;\n  height: 18px;\n"])));
export var ToastMessage = styled.p(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  margin: 0;\n  text-align: left;\n  height: 18px;\n  margin-left: -1px;\n  overflow: hidden;\n  text-overflow: ellipsis;\n  white-space: nowrap;\n"], ["\n  margin: 0;\n  text-align: left;\n  height: 18px;\n  margin-left: -1px;\n  overflow: hidden;\n  text-overflow: ellipsis;\n  white-space: nowrap;\n"])));
export var ToastIcon = styled.div(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  float: left;\n  margin-right: 15px;\n  margin-top: 5px;\n  width: 25px;\n  height: 25px;\n"], ["\n  float: left;\n  margin-right: 15px;\n  margin-top: 5px;\n  width: 25px;\n  height: 25px;\n"])));
var templateObject_1, templateObject_2, templateObject_3, templateObject_4;
//# sourceMappingURL=styled.js.map