var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import styled, { css } from 'styled-components';
import { theme as typeColors } from '../../tokens/themes';
export var StyledAvatar = styled.span(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  display: block;\n  position: relative;\n  width: ", "px;\n  height: ", "px;\n  padding: 1px;\n  border-radius: 50%;\n  color: ", ";\n  ", ";\n"], ["\n  display: block;\n  position: relative;\n  width: ", "px;\n  height: ", "px;\n  padding: 1px;\n  border-radius: 50%;\n  color: ", ";\n  ", ";\n"])), function (pr) { return pr.width; }, function (pr) { return pr.height; }, typeColors.light.color, function (pr) { return pr.isActive && isActiveProp; });
var isActiveProp = css(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  &::before {\n    content: '';\n    display: block;\n    position: absolute;\n    z-index: -1;\n    top: -4px;\n    left: -4px;\n    width: calc(100% + 8px);\n    height: calc(100% + 8px);\n    border-radius: 50%;\n    background: linear-gradient(\n      90deg,\n      rgba(3, 70, 75, 1) 0%,\n      rgba(69, 181, 46, 1) 35%,\n      rgba(21, 227, 145, 1) 100%\n    );\n  }\n"], ["\n  &::before {\n    content: '';\n    display: block;\n    position: absolute;\n    z-index: -1;\n    top: -4px;\n    left: -4px;\n    width: calc(100% + 8px);\n    height: calc(100% + 8px);\n    border-radius: 50%;\n    background: linear-gradient(\n      90deg,\n      rgba(3, 70, 75, 1) 0%,\n      rgba(69, 181, 46, 1) 35%,\n      rgba(21, 227, 145, 1) 100%\n    );\n  }\n"])));
var commonStyles = css(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  position: relative;\n  width: 100%;\n  height: 100%;\n  border-radius: 50%;\n  background: #eee;\n  color: ", ";\n"], ["\n  position: relative;\n  width: 100%;\n  height: 100%;\n  border-radius: 50%;\n  background: #eee;\n  color: ", ";\n"])), typeColors.light.color);
export var StyledImage = styled.img(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  ", ";\n  object-fit: cover;\n"], ["\n  ", ";\n  object-fit: cover;\n"])), commonStyles);
export var StyledSpan = styled.span(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  font-size: 24px;\n  font-weight: 700;\n  color: ", ";\n  ", ";\n"], ["\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  font-size: 24px;\n  font-weight: 700;\n  color: ", ";\n  ", ";\n"])), typeColors.light.color, commonStyles);
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5;
//# sourceMappingURL=styled.js.map