var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import styled from 'styled-components';
export var StyledAccordion = styled.div(templateObject_1 || (templateObject_1 = __makeTemplateObject([""], [""])));
export var StyledHeader = styled.h4(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  border: 1px solid rgb(222, 226, 230);\n  border-radius: 10px;\n  display: flex;\n  align-items: center;\n  background-color: rgb(248, 249, 250);\n  transition: background-color 200ms ease;\n  color: rgb(52, 58, 64);\n  &.open {\n    border-bottom-left-radius: 0;\n    border-bottom-right-radius: 0;\n  }\n  .accordion-toggle-button {\n    display: flex;\n    align-items: center;\n    padding: 18px 20px;\n    span {\n      border: solid rgb(52, 58, 64);\n      border-width: 0 2px 2px 0;\n      display: inline-block;\n      padding: 4px;\n      rotate: -45deg;\n    }\n    &.open {\n      span {\n        transform: translateY(-2px);\n        rotate: 45deg;\n      }\n    }\n  }\n\n  :hover {\n    cursor: pointer;\n    background-color: rgb(233, 236, 239);\n  }\n"], ["\n  border: 1px solid rgb(222, 226, 230);\n  border-radius: 10px;\n  display: flex;\n  align-items: center;\n  background-color: rgb(248, 249, 250);\n  transition: background-color 200ms ease;\n  color: rgb(52, 58, 64);\n  &.open {\n    border-bottom-left-radius: 0;\n    border-bottom-right-radius: 0;\n  }\n  .accordion-toggle-button {\n    display: flex;\n    align-items: center;\n    padding: 18px 20px;\n    span {\n      border: solid rgb(52, 58, 64);\n      border-width: 0 2px 2px 0;\n      display: inline-block;\n      padding: 4px;\n      rotate: -45deg;\n    }\n    &.open {\n      span {\n        transform: translateY(-2px);\n        rotate: 45deg;\n      }\n    }\n  }\n\n  :hover {\n    cursor: pointer;\n    background-color: rgb(233, 236, 239);\n  }\n"])));
export var StyledDescriptionWrapper = styled.div(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  overflow: hidden;\n"], ["\n  overflow: hidden;\n"])));
export var StyledDescription = styled.div(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  transition: transform 300ms ease;\n  font-weight: normal;\n  color: rgb(73, 80, 87);\n  &.open,\n  &.close {\n    padding: 12px;\n    border: 1px solid rgb(222, 226, 230);\n    border-bottom-left-radius: 10px;\n    border-bottom-right-radius: 10px;\n  }\n\n  &.close {\n    transform: translateY(-100%);\n  }\n"], ["\n  transition: transform 300ms ease;\n  font-weight: normal;\n  color: rgb(73, 80, 87);\n  &.open,\n  &.close {\n    padding: 12px;\n    border: 1px solid rgb(222, 226, 230);\n    border-bottom-left-radius: 10px;\n    border-bottom-right-radius: 10px;\n  }\n\n  &.close {\n    transform: translateY(-100%);\n  }\n"])));
var templateObject_1, templateObject_2, templateObject_3, templateObject_4;
//# sourceMappingURL=styled.js.map