var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import styled from 'styled-components';
import { theme as typeColors } from '../../tokens/themes';
export var StyledCard = styled.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  display: flex;\n  padding: 0.5rem;\n  margin-bottom: 0.5rem;\n  width: 100%;\n  @media (min-width: 40rem) {\n    width: 50%;\n  }\n  @media (min-width: 56rem) {\n    width: 33.3%;\n  }\n"], ["\n  display: flex;\n  padding: 0.5rem;\n  margin-bottom: 0.5rem;\n  width: 100%;\n  @media (min-width: 40rem) {\n    width: 50%;\n  }\n  @media (min-width: 56rem) {\n    width: 33.3%;\n  }\n"])));
export var StyledCardItem = styled.div(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  display: flex;\n  flex-direction: column;\n  overflow: hidden;\n  border-radius: 8px;\n  color: ", ";\n  text-decoration: none;\n  font-size: 15px;\n  background-color: ", ";\n  width: 100%;\n"], ["\n  display: flex;\n  flex-direction: column;\n  overflow: hidden;\n  border-radius: 8px;\n  color: ", ";\n  text-decoration: none;\n  font-size: 15px;\n  background-color: ", ";\n  width: 100%;\n"])), function (pr) { return (pr.type ? typeColors[pr.type].color : '#00000'); }, function (pr) { return pr.type && typeColors[pr.type].hover; });
export var StyledImage = styled.img(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  max-width: 100%;\n  height: 200px;\n  overflow: hidden;\n  background-size: cover;\n"], ["\n  max-width: 100%;\n  height: 200px;\n  overflow: hidden;\n  background-size: cover;\n"])));
export var StyledTitle = styled.h2(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  font-weight: 800;\n  margin: auto 17px;\n  margin-top: 1rem;\n"], ["\n  font-weight: 800;\n  margin: auto 17px;\n  margin-top: 1rem;\n"])));
export var StyledSubTitle = styled.h5(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n  margin: auto 17px;\n  margin-top: 0.5rem;\n"], ["\n  margin: auto 17px;\n  margin-top: 0.5rem;\n"])));
export var StyledDescription = styled.p(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n  display: flex;\n  flex: 1 1 auto;\n  flex-direction: column;\n  margin: auto 17px;\n  margin-top: 0.5rem;\n"], ["\n  display: flex;\n  flex: 1 1 auto;\n  flex-direction: column;\n  margin: auto 17px;\n  margin-top: 0.5rem;\n"])));
export var StyledFooter = styled.div(templateObject_7 || (templateObject_7 = __makeTemplateObject(["\n  color: ", ";\n  text-align: center;\n  display: flexbox;\n  justify-content: space-between;\n  padding: 20px 20px;\n"], ["\n  color: ", ";\n  text-align: center;\n  display: flexbox;\n  justify-content: space-between;\n  padding: 20px 20px;\n"])), function (pr) { return (pr.type ? typeColors[pr.type].color : '#00000'); });
export var StyledFooterText = styled.p(templateObject_8 || (templateObject_8 = __makeTemplateObject(["\n  text-align: left;\n  margin: auto 0px;\n  font-size: 14px;\n"], ["\n  text-align: left;\n  margin: auto 0px;\n  font-size: 14px;\n"])));
export var StyledFooterLink = styled.a(templateObject_9 || (templateObject_9 = __makeTemplateObject(["\n  color: #d193fa;\n  cursor: pointer;\n  text-decoration: none;\n  &:active,\n  &:visited {\n    color: #9357ba;\n    text-decoration: none;\n  }\n  &:focus,\n  &:hover {\n    color: #6874cc;\n  }\n"], ["\n  color: #d193fa;\n  cursor: pointer;\n  text-decoration: none;\n  &:active,\n  &:visited {\n    color: #9357ba;\n    text-decoration: none;\n  }\n  &:focus,\n  &:hover {\n    color: #6874cc;\n  }\n"])));
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7, templateObject_8, templateObject_9;
//# sourceMappingURL=styled.js.map